name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        S3_REPO_USERNAME: ${{ secrets.S3_REPO_USERNAME }}
        S3_REPO_PASSWORD: ${{ secrets.S3_REPO_PASSWORD }}
      run: mvn --settings settings.xml deploy
